apiVersion: v1
kind: ServiceAccount
metadata:
  name: wordpress-sa
  namespace: wordpress
  annotations:
    # Workload Identity binding
    # This binds the K8s SA to Google Cloud SA for Cloud SQL Proxy
    iam.gke.io/gcp-service-account: wordpress-cloudsql-sa@project-70763583-0169-48b4-8f8.iam.gserviceaccount.com
